services:
  postgres:
    container_name: api_log_db_container
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_log_db