# Dockerfile.postgres
FROM postgres:latest

RUN localedef -i ko_KR -c -f UTF-8 -A /usr/share/locale/locale.alias ko_KR.UTF-8

ENV LANG ko_KR.utf8
#    LC_COLLATE=ko_KR.utf8 \
#    POSTGRES_INITDB_ARGS=--data-checksums